### ISSUE TITLE
don't fail release action when release already exists

### ISSUE THREAD

**Issue by BenTheElder** [kind-ci/containerd-nightlies#18]
minor but we should fix this so it's easier to check the health of the pipeline at a glance instead of comparing releases to what exists in containerd
cc @aojea

**Comment by aojea** [comment]
It turns out github actions doesn't fail fast
Let see if this works
https://github.com/kind-ci/containerd-nightlies/commit/d317be2d288d9345d0c09ec391bdb637a3404d52

**Comment by aojea** [comment]
it seems it is working fine now
https://github.com/kind-ci/containerd-nightlies/runs/1966140140?check_suite_focus=true

**Comment by BenTheElder** [comment]
Thanks!
