### ISSUE TITLE
parse runc-version, not go.mod (vendor.conf)

### ISSUE THREAD

**Issue by AkihiroSuda** [kind-ci/containerd-nightlies#19]
https://github.com/kind-ci/containerd-nightlies/blob/fe506121b5d9af66a23af31ac2344bca0993c2db/.github/workflows/main.yml#L38-L44

This version detection logic is not robust.
As the result, https://github.com/kind-ci/containerd-nightlies/releases/tag/containerd-1.5.1 was released with an unexpected version of runc (expected: rc94, actual: rc93).

The right way is to read `script/setup/runc-version`.

https://github.com/containerd/containerd/blob/v1.4.5/script/setup/runc-version
https://github.com/containerd/containerd/blob/v1.5.1/script/setup/runc-version

**Comment by AkihiroSuda** [comment]
PR https://github.com/kind-ci/containerd-nightlies/pull/20

**Comment by BenTheElder** [comment]
thanks, the previous solution was rushed to unblock some kubernetes CI testing and is definitely not robust enough.

**Comment by BenTheElder** [comment]
I am re-running the nightlies after deleting v1.5.1 in particular.
