### ISSUE TITLE
zuul was removed upstream in main, need to get go version a different way

### ISSUE THREAD

**Issue by BenTheElder** [kind-ci/containerd-nightlies#23]
https://github.com/containerd/containerd/pull/7369

we can use .github/workflows/nightly.yml `GO_VERSION: '1.19.1'`

(we don't use upstream nightly builds still because they're harder to automatically consume, with paths like https://github.com/containerd/containerd/suites/8409151131/artifacts/371863559 => latest linux amd64 nightly build in a zip, and release builds)

we might be able to switch to upstream for _release_ versions though and lately we're shipping those more often than early tags, however in the past we needed to pick up fixes _ASAP_ so it's probably still worth maintaining here

cc @aojea

**Comment by BenTheElder** [comment]
upstream release builds do include multiple architectures now, but not s390x

**Comment by aojea** [comment]
:eye: https://github.com/containerd/containerd/commit/7787168ccc5f8d30614b1cb4b6572ac95c705f08

**Comment by BenTheElder** [comment]
yeah that's 

> we can use .github/workflows/nightly.yml GO_VERSION: '1.19.1'

**Comment by aojea** [comment]
https://github.com/kind-ci/containerd-nightlies/commit/6a40fce05ad23a799d25cd44aaedfe58702cbdff

**Comment by BenTheElder** [comment]
this broke the older branches, but if it's only 1.5 we can just drop 1.5 (I think it is?)
https://github.com/kind-ci/containerd-nightlies/actions/runs/3102826780

**Comment by aojea** [comment]
> this broke the older branches, but if it's only 1.5 we can just drop 1.5 (I think it is?) https://github.com/kind-ci/containerd-nightlies/actions/runs/3102826780

:) https://github.com/kind-ci/containerd-nightlies/commit/83bdecdbd2d8b565cf2d1f5787d11a11bb22087a
